Update rpm script to use npm ping rather than raw curl
to fix #61

diff --git a/rpm/update-nodejs-and-nodered b/rpm/update-nodejs-and-nodered
--- a/rpm/update-nodejs-and-nodered
+++ b/rpm/update-nodejs-and-nodered
@@ -158,9 +158,6 @@ then
   esac
 fi
 
-
-
-
 if [[ -z "${OPEN_FIREWALL}" ]] && [[ "${CONFIRM_INSTALL}" == "n" ]]
 then
   OPEN_FIREWALL="n"
@@ -190,17 +187,31 @@ esac
 [[ -n "${NODERED_HOME}" ]] || export NODERED_HOME="/home/${NODERED_USER}"
 
 
-# check internet, if failure exit
-if curl -f https://www.npmjs.com/package/node-red  >/dev/null 2>&1
-then
-  echo " "
+# # check internet, if failure exit
+# if curl -f https://www.npmjs.com/package/node-red  >/dev/null 2>&1
+# then
+#   echo " "
+# else
+#   echo " "
+#   echo "Sorry - cannot connect to internet - not going to touch anything."
+#   echo "https://www.npmjs.com/package/node-red   is not reachable."
+#   echo "Please ensure you have a working internet connection."
+#   echo " "
+#   exit 1
+# fi
+
+output=$(npm ping 2>&1)
+exit_code=$?
+
+if [ $exit_code -eq 0 ]; then
+    echo " "
 else
-  echo " "
-  echo "Sorry - cannot connect to internet - not going to touch anything."
-  echo "https://www.npmjs.com/package/node-red   is not reachable."
-  echo "Please ensure you have a working internet connection."
-  echo " "
-  exit 1
+    echo " "
+    echo "Sorry - cannot connect to internet - not going to touch anything."
+    echo "https://www.npmjs.com/package/node-red   is not reachable."
+    echo "Please ensure you have a working internet connection."
+    echo " "
+    return 1
 fi
 
 # final install details
@@ -415,4 +426,3 @@ EOF
         exit 1
     ;;
 esac
-
